id: IF678BBB9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T23:39:11+00:00'
last_modified: '2022-06-09T04:28:59.875672+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD411
  title: བོད་སྐད་ཚིག་རྐང་ཉིས་སྟོང་བསླབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EDF6:
      image_group_id: I2PD17828
      title: Volume 1 of bod skad tshig rkang nyis stong bslab/
      total_pages: 330
      order: 1
      base_file: EDF6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
