id: P008098
initial_creation_type: ocr
source_metadata:
  id: bdr:W3PD411
  title: བོད་སྐད་ཚིག་རྐང་ཉིས་སྟོང་བསླབ།
  author: ''
  volumes:
    a6a568e4a82a4f11bb5da703fc587883:
      image_group_id: I2PD17828
      title: ''
      volume_number: 1
      total_pages: 330
ebook_metadata:
  title: བོད་སྐད་ཚིག་རྐང་ཉིས་སྟོང་བསླབ།
  author: ''
  sku: P008098
  cover: cover.jpg
  layers:
  - pagination
