id: P008098
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 13:01:25.106557
source_metadata:
  id: bdr:W3PD411
  title: བོད་སྐད་ཚིག་རྐང་ཉིས་སྟོང་བསླབ།
  author: ''
  volumes:
    e79f9c681e5c4fbb8b7d8a88186b3b55:
      image_group_id: I2PD17828
      title: Volume 1 of bod skad tshig rkang nyis stong bslab/
      volume_number: 1
      total_pages: 330
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
